

services:
  trainer:
    build: .
    env_file: .env
    volumes:
      - ./mlruns:/app/mlruns
    stdin_open: true
    tty: true

  mlflow-ui:
    image: my-ml-app
    command: mlflow ui --host 0.0.0.0 --port 5001
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/app/mlruns

